# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ABSLOPE_approx <- function(start, Xmis, Y, a_prior, b_prior, sigma = 1.0, FDR = 0.05, tol = 1e-04, known_sigma = FALSE, max_iter = 100L, verbose = TRUE) {
    .Call('_ABSLOPE_ABSLOPE_approx', PACKAGE = 'ABSLOPE', start, Xmis, Y, a_prior, b_prior, sigma, FDR, tol, known_sigma, max_iter, verbose)
}

